import './globals.css'
import { GlobalStateProvider } from '@/context/globalState'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'College Event',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider>
          {children}
        </GlobalStateProvider></body>
    </html>
  )
}
